num1=int(input("Enter the first integer:"))
num2=int(input("Enter the second integer:"))
print(f"Addition:{num1+num2}")
print(f"Subtraction:{num1-num2}")
print(f"Multiplication:{num1*num2}")
print(f"Division:{num1/num2 if num2!=0 else'Cannot divide by zero'}")
